stages:
  get_data:
    cmd: python src/get_data.py
    deps:
      - src/get_data.py
    outs:
      - outputs/raw/
  tokenize_data:
    cmd: python src/tokenize_data.py
    deps:
      - src/tokenize_data.py
    outs:
      - outputs/tokenized/
  define_train_model:
    cmd: python src/define_train_model.py
    deps:
      - src/define_train_model.py
      - outputs/tokenized/  # Relies on processed datasets
      - config.json  # Files containing training configurations
    outs:
      - outputs/model.h5  # Model output path
    metrics:
      - outputs/metrics/metrics.json  #  Place indicator files in a separate directory
  predict:
    cmd: python src/predict.py
    deps:
      - src/predict.py