name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install lib-ml
      run: pip install .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --errors-only .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Save and Publish Model
      run: |
        python train_model.py
        # Add commands to upload model to a cloud or save it with a public link
        # Example: aws s3 cp model.pkl s3://yourbucket/model.pkl --acl public-read
