name: Python Application CI

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Debug current directory and list files
      run: |
        echo "Current working directory:"
        pwd
        echo "List of files in the current directory:"
        ls -la

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install lib-ml
      run: pip install .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        if [ $? -ne 0 ]; then exit 1; fi
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --fail-under=7 .

    - name: Save and Publish Model
      run: |
        python define_train_model.py
        # Add commands to upload model to a cloud or save it with a public link
        # Example: aws s3 cp model.pkl s3://yourbucket/model.pkl --acl public-read
